openapi: 3.0.3
info:
  title: pagoPa RTP - OpenAPI 3.x
  description: DESCRIPTION
  version: 0.0.1
  contact:
    email: cstar@pagopa.it
servers:
  - description: Development/Test
    url: https://api-rtp.dev.cstar.pagopa.it/rtp/v1
    x-internal: true
  - description: User Acceptance Test
    url: https://api-rtp.uat.cstar.pagopa.it/rtp/v1
    x-internal: false
  - description: Production
    url: https://api-rtp.cstar.pagopa.it/rtp/v1
    x-internal: false
tags:
  - name: rtps
    description: API Group aims to notify a pagoPa notice through Request To Pay (RTP)
paths:
  /rtps:
    post:
      tags:
        - rtps
      operationId: "createRtp"
      summary: "Create and send a new RTP from a pagoPa notice"
      description: "Create and send a new RTP from a pagoPa notice"
      security:
        - oAuth2: [ admin_rtp_send, write_rtp_send ]
      requestBody:
        description: "pagoPa notice's details to create as RTP"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRtp"
      responses:
        "201":
          description: "Request to pay created and sent"
          headers:
            Location:
              required: true
              description: "The location of created rtp"
              schema:
                $ref: "#/components/schemas/RtpLocation"
        "422":
          description: "The debtor is not activated by the Service Provider"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MismatchActivationErrorResponse'

components:
  schemas:
    AmountEuroCents:
      description: Amount for payments, in euro cents
      type: number
      minimum: 0
      maximum: 99999999999

    NoticeNumber:
      type: string
      pattern: "\\d{18}"
      description: "pagoPa notice's code"
      example: "311111111112222222"
      externalDocs:
        description: "See noticeNumber field"
        url: "https://docs.pagopa.it/sanp/appendici/primitive#verifypaymentnotice-1"

    Payee:
      type: object
      properties:
        payeeId:
          $ref: "#/components/schemas/PayeeId"
        name:
          type: string
          maxLength: 140
          description: "The name of payee (e.g. EC name or Company Name)"
          example: "Comune di Roma"
        protocolId:
          $ref: "#/components/schemas/ProtocolId"
      required:
        - payeeId
        - name

    Payer:
      type: object
      properties:
        payerId:
          $ref: "#/components/schemas/PayerId"
        name:
          type: string
          maxLength: 140
          description: "The name of payer."
          example: "Mario Rossi"
      required:
        - payerId
        - name

    PaymentNotice:
      type: object
      properties:
        noticeNumber:          
          $ref: "#/components/schemas/NoticeNumber"
        amount:
          $ref: "#/components/schemas/AmountEuroCents"
        description:
          type: string
          description: "The pagopa notice's description"
          maxLength: 140
        subject:
          type: string
          description: "The subject of payment ( e.g. TARI 2025 )"
          maxLength: 140
        expiryDate:
          type: string
          description: "The pagoPa notice's expiry date. Formatted as ISO 8601 [YYYY]-[MM]-[DD]"
          format: date
          example: "2024-12-03"

    PayerId:
      type: string
      description: "The id of the recipient of the request to pay. The id is the fiscal code"
      example: "ABCDEF12G34H567I"
          
    PayeeId:
      type: string
      pattern: "\\d{11}|\\d{16}"
      description: "The payee id (e.g. EC fiscal code)"
      example: "77777777777"
      externalDocs:
        description: "See idPA field"
        url: "https://docs.pagopa.it/sanp/appendici/primitive#paverifypaymentnotice"

    ProtocolId:
      type: string
      pattern: "^[ -~]{1,140}$"
      description: "The protocol id"
      example: "ABC/124"

    RtpId:
      type: string
      format: uuid
      description: "Request to pay unique id"

    RtpLocation:
      type: string
      description: "The location of created resource"
      format: url
      example: "https://domain.com/rtps/{rtpId}"

    CreateRtp:
      type: object
      properties:
        payee:
          $ref: "#/components/schemas/Payee"
        payer:
          $ref: "#/components/schemas/Payer"
        paymentNotice:
          $ref: "#/components/schemas/PaymentNotice"
      required:
        - paymentNotice
        - payer
        - payee

    MismatchActivationErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Debtor's fiscal code is not activated"
        details:
          type: string
          example: "The debtor's fiscal code provided is not activated by thr subject making the request."

  # ============================================================================
  # Security schemes.
  # ============================================================================
  securitySchemes:
    oAuth2:
      description: |
        A bearer token in the format of a JWS and conforms to the specifications
        included in RFC8725.
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /token
          refreshUrl: /token
          scopes:
            admin_rtp_send: Admin enabled to send RPTs.
            write_rtp_send: Send RTPs.
