name: Run Spectral on Pull Requests

on:
  pull_request:
    paths:
      - '**/api/**/*.yaml'
      - '**/api/**/*.yml'
  
permissions:
  checks: write

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      # Run Spectral
      - uses: stoplightio/spectral-action@2ad0b9302e32a77c1caccf474a9b2191a8060d83 #v0.8.11
        with:
          file_glob: '**/api/pagopa/(*.yaml|*.yml)'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
