name: Run Spectral on Pull Requests

on:
  pull_request:
    paths:
      - 'openapi/**/*.yaml'
      - 'openapi/**/*.yml'
  

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'openapi/**/(*.yaml|*.yml)'
